### ISSUE TITLE
ShopifyAPI::Order has wrong type for type `subtotal_price`

### ISSUE THREAD

**Issue by Woolworths** [Shopify/shopify-api-ruby#1021]
# Issue summary

ShopifyAPI::Order seems to have the wrong type for type `subtotal_price`.

When I run the following:
```
session = ShopifyAPI::Auth::Session.new(
  shop: [...],
  access_token: [...],
  scope: "read_inventory,read_orders,read_products"
)
shopify_orders = ShopifyAPI::Order.all(session: session)
shopify_orders.first.subtotal_price
```

I get the following error:
```
/Users/name/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10448/lib/types/configuration.rb:296:in `call_validation_error_handler_default': Return value: Expected type T.nilable(Float), got type String with value "0.10" (TypeError)
Caller: (irb):11
Definition: /Users/name/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify_api-11.1.0/lib/shopify_api/rest/resources/2022_07/order.rb:231
irb(main):012:0> shopify_orders.first.subtotal_price
/Users/name/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10448/lib/types/configuration.rb:296:in `call_validation_error_handler_default': Return value: Expected type T.nilable(Float), got type String with value "0.10" (TypeError)
Caller: (irb):12
Definition: /Users/name/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify_api-11.1.0/lib/shopify_api/rest/resources/2022_07/order.rb:231
```

As you can see here (and in the codebase), `subtotal_price` expects a `T.nilable(Float)` but instead receives a `String`.

I would expect `subtotal_price` to rather be more similar to `total_price` which instead receives a `T.nilable(String)` (which would make this error go away).

I am confused however, because `subtotal_price` looks like this in the [documentation](https://shopify.dev/api/admin-rest/2022-07/resources/order):
<img width="515" alt="Screen Shot 2022-09-25 at 6 17 56 pm" src="https://user-images.githubusercontent.com/6524227/192134492-75268450-2b34-476b-8831-084bc390be29.png">

Wouldn't we expect it to look more like `total_price`?
<img width="485" alt="Screen Shot 2022-09-25 at 6 19 42 pm" src="https://user-images.githubusercontent.com/6524227/192134532-d21d110f-df65-4ebf-8c38-3b1405d20893.png">

Nevertheless, there is a problem somewhere in here. I hope I am not mistaken and have supplied sufficient information.

## Specifications

- `shopify_api` version: shopify_api (11.1.0)
- Shopify API version used (example: `2020-07`): 2022-07

**Comment by Woolworths** [comment]
This is still an issue.
