### ISSUE TITLE
Failure on Zeitwerk 2.6.5

### ISSUE THREAD

**Issue by andyw8** [Shopify/shopify-api-ruby#1058]
```
bundle exec rake test:rest_wrappers

(...many failures...)

2454) Error:
Metafield202201Test#test_64:
Zeitwerk::SetupRequired: please, finish your configuration and call Zeitwerk::Loader#setup once all is ready
    /Users/andyw8/.gem/ruby/3.1.1/gems/zeitwerk-2.6.5/lib/zeitwerk/loader.rb:143:in `block in unload'
    /Users/andyw8/.gem/ruby/3.1.1/gems/zeitwerk-2.6.5/lib/zeitwerk/loader.rb:142:in `synchronize'
    /Users/andyw8/.gem/ruby/3.1.1/gems/zeitwerk-2.6.5/lib/zeitwerk/loader.rb:142:in `unload'
    /Users/andyw8/src/github.com/Shopify/shopify-api-ruby/lib/shopify_api/context.rb:83:in `load_rest_resources'
    /Users/andyw8/.gem/ruby/3.1.1/gems/sorbet-runtime-0.5.10438/lib/types/private/methods/call_validation.rb:157:in `bind_call'
    /Users/andyw8/.gem/ruby/3.1.1/gems/sorbet-runtime-0.5.10438/lib/types/private/methods/call_validation.rb:157:in `validate_call'
    /Users/andyw8/.gem/ruby/3.1.1/gems/sorbet-runtime-0.5.10438/lib/types/private/methods/call_validation.rb:89:in `block in create_validator_slow'
    /Users/andyw8/src/github.com/Shopify/shopify-api-ruby/lib/shopify_api/context.rb:77:in `setup'
```
Seems due to this:

> Attempting to eager load or reload without previously invoking setup now raises Zeitwerk::SetupRequired.

https://github.com/fxn/zeitwerk/blob/main/CHANGELOG.md#265-6-november-2022

We do call `loader.setup` in `lib/shopify_api.rb` but something else must be needed.

FYI @klenotiw @nelsonwittwer

**Comment by jaredbeck** [comment]
When will the constraint in the gemspec be lifted, please?

```
  s.add_runtime_dependency("zeitwerk", "~> 2.5", "< 2.6.5") # https://github.com/Shopify/shopify-api-ruby/issues/1058
```

It's preventing us from using new versions of zeitwerk.
