### ISSUE TITLE
ShopifyAPI::Errors::HttpResponseError ({"error_reference":"If you report this error, please include this id 136e7407-e353-4ecf-8a66-xxxxxxxxx

### ISSUE THREAD

**Issue by poojaskarale** [Shopify/shopify-api-ruby#1229]
I am facing this issue when I am trying to save Shopify theme's settings-
theme name - dawn 2.0
query -
setting_datas = ShopifyAPI::Asset.all(session: shopify_session, asset: {key: 'config/settings_data.json'}, theme_id: publish_theme_id)
setting_datas[0].save

error -
ShopifyAPI::Errors::HttpResponseError ({"error_reference":"If you report this error, please include this id 136e7407-e353-4ecf-8a66-xxxxxxxxx

Please help me here

**Comment by aryansharma-16** [comment]
Facing the same issue for Asset API since a month while writing and having same error for Metafield API since yesterday

**Comment by aryansharma-16** [comment]
hi @nelsonwittwer, following are the steps to reproduce this error

```
shop=Shop.last

shop.with_shopify_session do 
  @found_theme = ShopifyAPI::Theme.all&.find{|theme| theme.role == 'main'}
end

shop.with_shopify_session do
  asset = ShopifyAPI::Asset.all(theme_id: @found_theme.id, asset: {key: 'sections/main-product.liquid'}).last
  lines = asset.value.lines
  body = []
  lines.each do |line|
    body << line
    body << "{% comment %} a piece of code from codebase {% endcomment %}\n" if(line =~ /{%- case block.type -%}/)
  end
  asset.value = body.join
  asset.save!
end
```
this is giving following error
```gems/ruby-3.1.2/gems/shopify_api-13.1.0/lib/shopify_api/clients/http_client.rb:71:in `request': {"error_reference":"If you report this error, please include this id: 159f7eca-c122-4b02-8dda-7560b70c1365."} (ShopifyAPI::Errors::HttpResponseError)```

while debugging, in [repository](https://github.com/Shopify/shopify-api-ruby/blob/main/lib/shopify_api/clients/http_client.rb) I found the code below which eleminates the possibility of this error being 500-
 ```
unless [429, 500].include?(response.code)
      raise ShopifyAPI::Errors::HttpResponseError.new(response: response), error_message
 end
```

**Comment by aryansharma-16** [comment]
@nelsonwittwer  the ID `159f7eca-c122-4b02-8dda-7560b70c1365` I provided, I tried to execute it just before posting the comment here, i.e you can check logs for today also.
In case you don't find that, here's another ID `82df3b5f-ed0f-4776-861a-f77e5f43f588` I tried this on 19th Oct
Thanks

**Comment by nelsonwittwer** [comment]
Thanks! I see it in the log and can use this help to try and track down the
root issue.

**Comment by poojaskarale** [comment]
@nelsonwittwer , here are the details -

3:49 am
Friday, 27 October 2023
Coordinated Universal Time (UTC)

shop = Shop.find_by_shopify_domain('demo-hulk-pooja.myshopify.com')
shopify_session = ShopifyAPI::Auth::Session.new(shop: shop.shopify_domain, access_token: shop.shopify_token)
setting_datas = ShopifyAPI::Asset.all(session: shopify_session, asset: {key: 'config/settings_data.json'}, theme_id: theme_id)
setting_data = setting_datas[0]
setting_data.save!

error - 
Traceback (most recent call last):
        1: from (irb):5
ShopifyAPI::Errors::HttpResponseError ({"error_reference":"If you report this error, please include this id: 71796e82-144e-4aa1-a5f2-2d1b7713ab6e."})

**Comment by immakdas** [comment]
I have permission to use Asset resource PUT or DEL requests in my app. So when I try to save the Asset with API 2023-10 and 2023-04 I get the errors like
`error: {"error_reference":"If you report this error, please include this id: b155c963-74e0-4014-8f23-6e610b2789c2."}`

Could you please reopen the ticket and resolve the bug? Half of the Shopify merchants use old themes and we developers are required to use AssetAPI. (app already has theme-app-ext ....)

Hope the RUBY backtrace helps to find the cause
```
backtrace ["/.rvm/gems/ruby-3.2.2/gems/shopify_api-13.3.1/lib/shopify_api/clients/http_client.rb:75:in `request'", "/.rvm/gems/ruby-3.2.2/gems/sorbet-runtime-0.5.11150/lib/types/private/methods/call_validation_2_7.rb:108:in `bind_call'", "/.rvm/gems/ruby-3.2.2/gems/sorbet-runtime-0.5.11150/lib/types/private/methods/call_validation_2_7.rb:108:in `block in create_validator_method_fast1'", "/.rvm/gems/ruby-3.2.2/gems/shopify_api-13.3.1/lib/shopify_api/clients/rest/admin.rb:68:in `put'", "/.rvm/gems/ruby-3.2.2/gems/sorbet-runtime-0.5.11150/lib/types/private/methods/call_validation.rb:153:in `bind_call'", "/.rvm/gems/ruby-3.2.2/gems/sorbet-runtime-0.5.11150/lib/types/private/methods/call_validation.rb:153:in `validate_call_skip_block_type'", "/.rvm/gems/ruby-3.2.2/gems/sorbet-runtime-0.5.11150/lib/types/private/methods/call_validation.rb:95:in `block in create_validator_slow_skip_block_type'", "/.rvm/gems/ruby-3.2.2/gems/shopify_api-13.3.1/lib/shopify_api/rest/base.rb:345:in `public_send'", "/.rvm/gems/ruby-3.2.2/gems/shopify_api-13.3.1/lib/shopify_api/rest/base.rb:345:in `save'", "/.rvm/gems/ruby-3.2.2/gems/sorbet-runtime-0.5.11150/lib/types/private/methods/call_validation.rb:153:in `bind_call'", 
"/.rvm/gems/ruby-3.2.2/gems/sorbet-runtime-0.5.11150/lib/types/private/methods/call_validation.rb:153:in `validate_call_skip_block_type'", 
"/.rvm/gems/ruby-3.2.2/gems/sorbet-runtime-0.5.11150/lib/types/private/methods/call_validation.rb:95:in `block in create_validator_slow_skip_block_type'", ....
````
