### ISSUE TITLE
ShopifyAPI::InventoryLevel.find: ArgumentError `element_path': wrong number of arguments (given 3, expected 0..2) 

### ISSUE THREAD

**Issue by sshaw** [Shopify/shopify-api-ruby#587]
v6.0

```rb
ShopifyAPI::InventoryLevel.find(variant.inventory_item_id)
```

Results in:

```
/Users/sshaw/.rvm/gems/ruby-2.3.7/gems/shopify_api-6.0.0/lib/shopify_api/resources/inventory_level.rb:13:in `element_path': wrong number of arguments (given 3, expected 0..2) (ArgumentError)
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/activeresource-5.1.0/lib/active_resource/base.rb:1096:in `find_single'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/activeresource-5.1.0/lib/active_resource/base.rb:984:in `find'
	from xxx.rb:62:in `block in set_dates'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/shopify_api-6.0.0/lib/shopify_api/session.rb:29:in `temp'
...
```

**Comment by sshaw** [comment]
Ah, I see issue: `InventoryLevel` doesn't support a GET this way. Nevertheless if there's no "find" then one shouldn't be able to call `.find`.
