### ISSUE TITLE
Shopify::Base.connection.response nil for private apps

### ISSUE THREAD

**Issue by joeshin** [Shopify/shopify-api-ruby#715]
```
$ cat orders.rb
```
```ruby
require 'shopify_api'
require 'pry'

def initialize
  shop_url = "https://#{ENV['SHOPIFY_API_KEY']}:#{ENV['SHOPIFY_PASSWORD']}@#{ENV['SHOPIFY_SHOP_NAME']}.myshopify.com"
  ShopifyAPI::Base.site = shop_url
  ShopifyAPI::Base.api_version = '2020-01'
end

initialize
orders = ShopifyAPI::Order.find(:all, params: { limit: 35, stats: :any })
```

```
$ bundle exec ruby orders.rb
Traceback (most recent call last):
	6: from orders.rb:12:in `<main>'
	5: from /usr/local/var/rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activeresource-5.1.0/lib/active_resource/base.rb:974:in `find'
	4: from /usr/local/var/rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activeresource-5.1.0/lib/active_resource/base.rb:1073:in `find_every'
	3: from /usr/local/var/rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activeresource-5.1.0/lib/active_resource/base.rb:1101:in `instantiate_collection'
	2: from /usr/local/var/rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activeresource-5.1.0/lib/active_resource/base.rb:1101:in `new'
	1: from /usr/local/var/rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/shopify_api-9.0.0/lib/shopify_api/paginated_collection.rb:7:in `initialize'
/usr/local/var/rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/shopify_api-9.0.0/lib/shopify_api/paginated_collection.rb:52:in `pagination_link_headers': undefined method `[]' for nil:NilClass (NoMethodError)
```

Digging through the code it seems that the response is always nil.  The response body however does contain the expected orders, it's just breaking on pagination.

Even stranger, no issues when using the same install on a public app `ShopifyAPI::Order.find(:all, params: { limit: 35, stats: :any })`.

So requests are being made, auth is good, results are present, just that `Shopify::Base.connection.response` is `nil` and barfs trying to get `Shopify::Base.connection.response["Link"]`.

It does look like `ResponseCapture` is being prepended properly and `handle_response` is being called (I'm actually not 100% sure if this is responsible for setting the response but thought I'd include it anyhow).

```
[1] pry(#<ShopifyAPI::Connection>)> @response = super(ShopifyAPI::MessageEnricher.new(response))
=> #<Net::HTTPOK 200 OK readbody=true>
```

Let me know if I can provide more details.

**Comment by joeshin** [comment]
Any idea if I'm just being an idiot or if this is a real issue?
